import NavBar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";
import { ClerkProvider, SignIn } from "@clerk/nextjs";
import { SignedIn } from "@clerk/nextjs/app-beta";
import { SignedOut } from "@clerk/nextjs/app-beta/client";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <SignedIn>

          <NavBar />
          {children}
          <Footer />

          </SignedIn>

          <SignedOut>
            <SignIn/>
          </SignedOut>
        </body>
      </html>
    </ClerkProvider>
  );
}
